import _compression
import types
from ._frame import compress as compress, compress_begin as compress_begin, compress_chunk as compress_chunk, compress_flush as compress_flush, create_compression_context as create_compression_context, create_decompression_context as create_decompression_context, decompress as decompress, decompress_chunk as decompress_chunk, get_frame_info as get_frame_info, reset_decompression_context as reset_decompression_context
from _typeshed import Incomplete

__doc__: Incomplete
BLOCKSIZE_DEFAULT: Incomplete
BLOCKSIZE_MAX64KB: Incomplete
BLOCKSIZE_MAX256KB: Incomplete
BLOCKSIZE_MAX1MB: Incomplete
BLOCKSIZE_MAX4MB: Incomplete
COMPRESSIONLEVEL_MIN: int
COMPRESSIONLEVEL_MINHC: int
COMPRESSIONLEVEL_MAX: int

class LZ4FrameCompressor:
    block_size: Incomplete
    block_linked: Incomplete
    compression_level: Incomplete
    content_checksum: Incomplete
    block_checksum: Incomplete
    auto_flush: Incomplete
    return_bytearray: Incomplete
    def __init__(self, block_size=..., block_linked: bool = True, compression_level=..., content_checksum: bool = False, block_checksum: bool = False, auto_flush: bool = False, return_bytearray: bool = False) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exception_type: type[BaseException] | None, exception: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def begin(self, source_size: int = 0): ...
    def compress(self, data): ...
    def flush(self): ...
    def reset(self) -> None: ...
    def has_context(self): ...
    def started(self): ...

class LZ4FrameDecompressor:
    eof: bool
    needs_input: bool
    unused_data: Incomplete
    def __init__(self, return_bytearray: bool = False) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exception_type: type[BaseException] | None, exception: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def reset(self) -> None: ...
    def decompress(self, data, max_length: int = -1): ...

class LZ4FrameFile(_compression.BaseStream):
    def __init__(self, filename=None, mode: str = 'r', block_size=..., block_linked: bool = True, compression_level=..., content_checksum: bool = False, block_checksum: bool = False, auto_flush: bool = False, return_bytearray: bool = False, source_size: int = 0) -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self): ...
    def fileno(self): ...
    def seekable(self): ...
    def readable(self): ...
    def writable(self): ...
    def peek(self, size: int = -1): ...
    def readall(self): ...
    def read(self, size: int = -1): ...
    def read1(self, size: int = -1): ...
    def readline(self, size: int = -1): ...
    def write(self, data): ...
    def flush(self) -> None: ...
    def seek(self, offset, whence=...): ...
    def tell(self): ...

def open(filename, mode: str = 'rb', encoding=None, errors=None, newline=None, block_size=..., block_linked: bool = True, compression_level=..., content_checksum: bool = False, block_checksum: bool = False, auto_flush: bool = False, return_bytearray: bool = False, source_size: int = 0): ...
