from _typeshed import ReadableBuffer
from io import BufferedIOBase, RawIOBase
from collections.abc import Callable

class BaseStream(BufferedIOBase): ...

class DecompressReader(RawIOBase):
    def __init__(
        self,
        fp: BufferedIOBase,
        decomp_factory: Callable[..., object],
        /,
        *,
        trailing_error: Callable[[], object] = ...,
    ) -> None: ...
    def close(self) -> None: ...
    def readable(self) -> bool: ...
    def readinto(self, b: ReadableBuffer) -> int: ...
    def read(self, size: int | None = -1, /) -> bytes: ...
    def readall(self) -> bytes: ...
    def readline(self, size: int | None = -1, /) -> bytes: ...
    def seek(self, offset: int, whence: int = 0, /) -> int: ...
    def seekable(self) -> bool: ...
    def tell(self) -> int: ...
